version: "3.6"
services:
    httpsaurus:
        image: ghostwritten/server:latest
        ports:
            - "80:8080"
            - "443:8443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
volumes:
