
type User @secret(field: "password")
{
    username: String! @id
}

type Query
{
    request: String @custom(http: {
        url: "${SERVER_GRAPHQL}"
        method: "POST",
        graphql: "query { request }"
        skipIntrospection: true
    })
}
input Email
{
    from: String!
    to: [String]!
    replyTo: String
    subject: String
    text: String
    html: String
}
type EmailResult @remote
{
    success: Boolean!
    errors: [String]
}
type Mutation
{
    sendEmail(email: Email!): EmailResult @custom(http: {
        url: "${SERVER_GRAPHQL}"
        method: "POST",
        graphql: "mutation($email: Email!) { sendEmail(email: $email) }"
    })
}
